[Profile]
Name="AibaUiha"
DBName="UihaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/AibaUiha"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCnRQYHTnRLSF0cLJwMnedCg"