[Profile]
Name="AizonoManami"
DBName="AizonoChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/manami_aizono"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC0WwEfE-jOM2rzjpdfhTzZA"