[Profile]
Name="AkabaneYouko"
DBName="AkabaneChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/Youko_Akabane"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="AkabaneChannel"