[Profile]
Name="AkabaneYouko"
DBName="AkabaneChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Youko_Akabane"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCBi8YaVyZpiKWN3_Z0dCTfQ"