[Profile]
Name="AmamiyaKokoro"
DBName="AmamiyaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/amamiya_kokoro"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCkIimWZ9gBJRamKF0rmPU8w"