[Profile]
Name="AmemoriSayo"
DBName="AmemoriChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Sayo_Amemori"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCRWOdwLRsenx2jLaiCAIU4A"