[Profile]
Name="AsukaHina"
DBName="AsukaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/hina__asuka"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCiSRx1a2k-0tOg-fs6gAolQ"