[Profile]
Name="Elu"
DBName="EluChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Elu_World"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCYKP16oMX9KKPbrNgo_Kgag"