[Profile]
Name="EmmaAugust"
DBName="EmmaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/emma_august_"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCl1oLKcAq93p-pwKfDGhiYQ"