[Profile]
Name="Fumi"
DBName="FumiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/FumiVirtual"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCwrjITPwG4q71HzihV2C7Nw"