[Profile]
Name="FurenELustalio"
DBName="FurenChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/furen_2434"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCuep1JCrMvSxOGgGhBfJuYw"