[Profile]
Name="FuwaMinato"
DBName="FuwaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/Fuwa_Minato"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC6wvdADTJ88OfIbJYIpAaDA"