[Profile]
Name="GundouMirei"
DBName="GundouChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/g9v9g_mirei"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCeShTCVgZyq2lsBW9QwIJcw"