[Profile]
Name="HanabatakeChaika"
DBName="HanabatakeChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/ZulmIhP1nlMOT5y"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCsFn_ueskBkMCEyzCEqAOvg"