[Profile]
Name="HarusakiAir"
DBName="HarusakiChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/harusakiair2434"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCtAvQ5U0aXyKwm2i4GqFgJg"