[Profile]
Name="HayamaMarin"
DBName="HayamaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Hayama_Marin"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCfipDDn7wY-C-SoUChgxCQQ"