[Profile]
Name="HayaseSou"
DBName="HayaseChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/SouHayase"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC2OacIzd2UxGHRGhdHl1Rhw"