[Profile]
Name="HoshikawaSara"
DBName="HoshikawaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Sara_Hoshikawa"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC9V3Y3_uzU5e-usObb6IE1w"