[Profile]
Name="Ibrahim"
DBName="IbrahimChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/honmono_ibrahim"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCmZ1Rbthn-6Jm_qOGjYsh5A"