[Profile]
Name="IenagaMugi"
DBName="IenagaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/ienaga_mugi23"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC_GCs6GARLxEHxy1w40d6VQ"