[Profile]
Name="InuiToko"
DBName="InuiChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/inui_toko"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCXRlIK3Cw_TJIQC5kSJJQMg"