[Profile]
Name="IzumiKasumi"
DBName="IzumiChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/ikasumi_zzz"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCLpYMk5h1bq8_GAFVBgXhPQ"