[Profile]
Name="IzumoKasumi"
DBName="IzumoChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/ikasumi_zzz"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCLpYMk5h1bq8_GAFVBgXhPQ"