[Profile]
Name="JoeRikiichi"
DBName="RikiichiChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/JoeRikiichi"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UChUJbHiTVeGrSkTdBzVfNCQ"