[Profile]
Name="KandaShoichi"
DBName="KandaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/Kanda_Shoichi"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCWz0CSYCxf4MhRKPDm220AQ"