[Profile]
Name="KataribeTsumugu"
DBName="KataribeChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/KataribeTsumugu"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCufQu4q65z63IgE4cfKs1BQ"