[Profile]
Name="KingyozakaMeiro"
DBName="MeiroChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/meiro_oO"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC69URn8iP4u8D_zUp-IJ1sg"