[Profile]
Name="LainPaterson"
DBName="LainChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Lain_Paterson"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCRm6lqtdxs_Qo6HeL-SRQ-w"