[Profile]
Name="LaurenIroas"
DBName="LaurenChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Lauren_iroas"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCgmFrRcyH7d1zR9sIVQhFow"