[Profile]
Name="LeosVincent"
DBName="LeosChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Leos_Vincent"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC-6rZgmxZSIbq786j3RD5ow"