[Profile]
Name="LuisCammy"
DBName="LuisChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Luis_Cammy"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCb6ObE-XGCctO3WrjRZC-cw"