[Profile]
Name="MachitaChima"
DBName="ChimaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/chima_machita23"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCo7TRj3cS-f_1D9ZDmuTsjw"