[Profile]
Name="MaimotoKeisuke"
DBName="MaimotoChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/maimoto_k"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCJubINhCcFXlsBwnHp0wl_g"