[Profile]
Name="MayuzumiKai"
DBName="MayuzumiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/mayuzumi_X"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCb5JxV6vKlYVknoJB8TnyYg"