[Profile]
Name="MelissaKinrenka"
DBName="MelissaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/melissa_2434"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCwcyyxn6h9ex4sMXGtpQE_g"