[Profile]
Name="Moira"
DBName="MoiraChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/Moiramoimoimoi"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCvmppcdYf4HOv-tFQhHHJMA"