[Profile]
Name="NagaoKei"
DBName="KeiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/kei_nagao2434"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCXW4MqCQn-jCaxlX-nn-BYg"