[Profile]
Name="NijisanjiOfficial"
DBName="NijisanjiOfficialChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/nijisanji_app"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCX7YkU9nEeaoZbkVLVajcMg"