[Profile]
Name="NuiSociere"
DBName="NuiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Nui_Sociere"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCUc8GZfFxtmk7ZwSO7ccQ0g"