[Profile]
Name="OliverEvans"
DBName="OliverChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/oliverD_23"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCqjTqdVlvIipZXIKeCkHKUA"