[Profile]
Name="OnomachiHaruka"
DBName="OnomachiChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/onomachi_haruka"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCg63a3lk6PNeWhVvMRM_mrQ"