[Profile]
Name="OtogibaraEra"
DBName="OtogibaraChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/OtogibaraEra"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCwQ9Uv-m8xkE5PzRc7Bqx3Q"