[Profile]
Name="RatnaPetit"
DBName="RatnaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/ratna_petit"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCIG9rDtgR45VCZmYnd-4DUw"