[Profile]
Name="RindouMikoto"
DBName="RindouChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/RindouMikoto"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCPvGypSgfDkVe7JG2KygK7A"