[Profile]
Name="RyuShen"
DBName="MidoriChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/midori_2434"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCt5-0i4AVHXaWJrL8Wql3mw"