[Profile]
Name="SasakiSaku"
DBName="SasakiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/saku_sasaki"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCoztvTULBYd3WmStqYeoHcA"