[Profile]
Name="ShibuyaHajime"
DBName="ShibuyaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/sibuya_hajime"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCeK9HFcRZoTrvqcUCtccMoQ"