[Profile]
Name="ShidukaRin"
DBName="ShidukaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/ShizuRin23"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC6oDys1BGgBsIC3WhG1BovQ"