[Profile]
Name="ShiinaYuika"
DBName="ShiinaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/yuika_siina"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC_4tXjqecqox5Uc05ncxpxg"