[Profile]
Name="ShirayukiTomoe"
DBName="TomoeChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Tomoe_Shirayuki"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCuvk5PilcvDECU7dDZhQiEw"