[Profile]
Name="SukoyaKana"
DBName="SukoyaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/sukosuko_sukoya"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC8C1LLhBhf_E2IBPLSDJXlQ"