[Profile]
Name="SuoSango"
DBName="SangoChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/Suo_Sango"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCL_O_HXgLJx3Auteer0n0pA"