[Profile]
Name="SuzukaUtako"
DBName="UtakoChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/suzukautako"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCwokZsOK_uEre70XayaFnzA"