[Profile]
Name="SuzuyaAki"
DBName="SuzuyaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/aki_suzuya"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCpnvhOIJ6BN-vPkYU9ls-Eg"