[Profile]
Name="TakamiyaRion"
DBName="TakamiyaChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/TakamiyaRion"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCV5ZZlLjk5MKGg3L0n0vbzw"