[Profile]
Name="TodorokiKyoko"
DBName="KyokoChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/KT_seeds"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCRV9d6YCYIMUszK-83TwxVA"