[Profile]
Name="TsukinoMito"
DBName="MitoChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/MitoTsukino"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCD-miitqNY3nyukJ4Fnf4_A"