[Profile]
Name="UshimiIchigo"
DBName="IchigoChannel"
Member="Nijisanji"
Affiliation="Ichikara"
Twitter="https://twitter.com/ushimi_ichigo"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCmUjjW5zF1MMOhYUwwwQv9Q"