[Profile]
Name="UzukiKou"
DBName="UzukiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/udukikohh"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC3lNFeJiTq6L3UWoz4g1e-A"