[Profile]
Name="YorumiRena"
DBName="YorumiChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/rena_yorumi"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCL34fAoFim9oHLbVzMKFavQ"