[Profile]
Name="YuzukiRoa"
DBName="RoaChannel"
Member="Nijisanji"
Affiliation="AnyColor"
Twitter="https://twitter.com/yuzuki_roa"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCCVwhI5trmaSxfcze_Ovzfw"