[Profile]
Name="ShirakamiFubuki"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/shirakamifubuki"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCdn5BQ06XqgXoAxIhbqw5Rg"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=332704117