[Profile]
Name=""
DBName=""
Member=""
Affiliation=""
Twitter=""

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID=""

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    # ID=