[Profile]
Name=""
DBName=""
Member=""
Affiliation=""
Twitter=""

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID=""
    # If the user has a subchannel, be sure to put it second.
    # [[ChannelData.Details]]
    # ID=""

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    # ID=