[Profile]
Id=6516462878389261
Name="AkaiHaato"
DBName="HaatoChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/akaihaato"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC1CfXB_kRs3C-zaeTG3oGyg"