Id=9558276457337374
Name="AkiRosenthal"
DBName="akiroseChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/akirosenthal"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCFTLzh12_nrtzqBPsTCqenA"