[Profile]
Name="AmaneKanata"
DBName="KanataChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/amanekanatach"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCZlDXzGoo7d44bwdNObFacg"