[Profile]
Name="AZKi"
DBName="AZKiChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/AZKi_VDiVA"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC0TXe_LYZ4scaW2XMyi5_kw"