[Profile]
Name="HimemoriLuna"
DBName="LunaChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/himemoriluna"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCa9Y57gfeY0Zro_noHRVrnw"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=491474052