[Profile]
Name="HoshimachiSuisei"
DBName="SuiseiChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/suisei_hosimati"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC5CwaMl1eIgY8h02uZw7u8A"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=9034870