[Profile]
Name="HoshouMarine"
DBName="MarineChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/houshoumarine"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCCzUftO8KOVkV4wQG1vkUvg"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=454955503