[Profile]
Name="InugamiKorone"
DBName="KoroneChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/inugamikorone"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UChAnqc_AY5_I3Px5dig3X1Q"