[Profile]
Name="KazamaIroha"
DBName="IrohaChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/kazamairohach"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC_vMYWcDjmfdpH6r4TTn1MQ"