[Profile]
Name="KiryuuCoco"
DBName="CocoChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/kiryucoco"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCS9uQI-jC3DE0L4IpXyvr6w"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=491474049