[Profile]
Name="ManoAloe"
DBName="AloeChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/manoaloe"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCgZuwn-O7Szh9cAgHqJ6vjw"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=624252711