[Profile]
Name="MinatoAqua"
DBName="AquaChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/minatoaqua"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC1opHUrw8rvnsadT-iGp7Cg"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=375504219