[Profile]
Name="MomosuzuNene"
DBName="NeneChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/momosuzunene"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCAWSyEs_Io8MtpY3m-zqILA"