[Profile]
Name="MurasakiShion"
DBName="ShionChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/murasakishionch"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCXTpFs_3PqI41qX2d9tL2Rw"