[Profile]
Name="NakiriAyame"
DBName="NakiriChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/nakiriayame"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC7fk0CB07ly8oSl0aqKkqFg"