[Profile]
Name="NekomataOkayu"
DBName="OkayuChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/nekomataokayu"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCvaTdHTWBGv3MKj3KVqJVCw"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=412135222