[Profile]
Name="OmaruPolka"
DBName="PolkaChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/omarupolka"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCK9V2B22uJYu3N7eR_BT9QA"