[Profile]
Name="OokamiMio"
DBName="MioChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/ookamimio"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCp-5t9SrOQwXMU7iIjQfARg"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=389862071