[Profile]
Name="Roboco"
DBName="RobocoChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/robocosan"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCDqI2jOz0weumE8s7paEk6g"