[Profile]
Name="Sakuramiko"
DBName="MikoChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/sakuramiko35"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC-hM6YJuNYVAmUWxeIr9FeA"