[Profile]
Name="FlareKorone"
DBName="FlareChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/shiranuiflare"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCvInZx9h3jC2JzsIzoOebWg"