[Profile]
Name="ShirakamiFubuki"
DBName="FubukiChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/shirakamifubuki"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCdn5BQ06XqgXoAxIhbqw5Rg"