[Profile]
Name="ShiroganeNoel"
DBName="NoelChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/shiroganenoel"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCdyqAaZDKHXg4Ahi7VENThQ"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=454733056