[Profile]
Name="ShishiroBotan"
DBName="BotanChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/shishirobotan"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCUKD-uaobj9jiqB-VXt71mA"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=624252710