[Profile]
Name="TakaneLui"
DBName="LuiChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/takanelui"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCs9_O1tRPMQTHQ-N_L6FU2g"