[Profile]
Name="TokinoSora"
DBName="SoraChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/tokino_sora"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCp6993wxpyDPHUpavwDFqgg"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=286179206