[Profile]
Name="TokoyamiTowa"
DBName="TowaChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/tokoyamitowa"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC1uv2Oq6kNxgATlCiez59hw"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=491474051