[Profile]
Name="TsunomakiWatame"
DBName="WatameChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/tsunomakiwatame"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCqm3BQLlJfvkTsX_hvm0UmA"