[Profile]
Name="UruhaRushia"
DBName="RushiaChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/uruharushia"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCl_gCybOJRIgOXw6Qb4qJzQ"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=443300418