[Profile]
Name="UsadaPekora"
DBName="PekoraChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/usadapekora"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC1DCedRgGHBdm81E1llLhOQ"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=443305053