[Profile]
Name="YozoraMel"
DBName="MelChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/yozoramel"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCD8HOxPs4Xvsm8H0ZxXGiBw"