[Profile]
Name="YukihanaLamy"
DBName="LamyChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/yukihanalamy"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UCFKOVgVbGmX65RxO3EtH3iw"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=624252706