[Profile]
Name="YuzukiChoco"
DBName="ChocoChannel"
Member="Hololive"
Affiliation="Cover"
Twitter="https://twitter.com/yuzukichococh"

[[ChannelData]]
SiteName="Youtube"
    [[ChannelData.Details]]
    ID="UC1suqwovbL1kzsoaZgFZLKg"
    [[ChannelData.Details]]
    ID="UCp3tgHXw_HI0QMk1K8qh3gQ"

[[ChannelData]]
SiteName="BiliBili"
    [[ChannelData.Details]]
    ID=389858754